{ config, pkgs, lib, ... }:

# Emacs. Nix owns the binary, native-comp toolchain and every binary Emacs
# shells out to. straight.el owns all elisp. Do not add elisp packages here:
# two package managers on one load-path is the failure mode.

let
  emacsPkg = pkgs.emacs30-pgtk;
in
{
  environment.systemPackages = [
    emacsPkg

    # straight clones and byte-compiles at runtime, so the toolchain has to
    # be present on the system, not just at build time.
    pkgs.git
    pkgs.gnutls          # url-retrieve over https, and straight's fetches
    pkgs.gcc
    pkgs.libgccjit       # native-comp
    pkgs.gnumake
    pkgs.cmake           # vterm, if your config uses it
    pkgs.libtool
    pkgs.ncurses

    # Things your config reaches for.
    pkgs.ripgrep
    pkgs.fd
    pkgs.imagemagick
    pkgs.sqlite
    pkgs.texliveSmall    # org to PDF
    pkgs.aspell
    # aspell has no en_AU dictionary; en carries the British/Australian
    # variants. Set them per-buffer with:
    #   (setq ispell-dictionary "en_AU")
    # after ispell-program-name is aspell, or use hunspell if you want a
    # dedicated en_AU. aspellDicts.en-computers is handy for code buffers.
    pkgs.aspellDicts.en
    pkgs.aspellDicts.en-computers

    # early-init.el sets auth-sources to a .gpg file, so gpg must be present
    # before the first frame. pinentry is configured in modules/devops.nix.
    pkgs.gnupg
  ];

  services.emacs = {
    enable = true;
    package = emacsPkg;
    defaultEditor = true;
    startWithGraphical = true;
  };

  # services.emacs.defaultEditor already sets EDITOR to nixpkgs' `emacseditor`
  # wrapper, which is emacsclient with a fallback to a fresh Emacs. Setting
  # EDITOR here as well is a hard conflict, so only VISUAL is declared, and
  # with mkDefault so anything more specific still wins.
  environment.variables.VISUAL = lib.mkDefault "emacseditor";

  # Merges with the unit generated by services.emacs above rather than
  # replacing it, which is the difference between this working and the
  # daemon losing its ExecStart.
  systemd.user.services.emacs = {
    # The module already sets unitConfig.After = "graphical-session.target"
    # as a plain string, so adding our own `after` list is a conflicting
    # definition rather than a merge. mkForce with BOTH values is the fix;
    # dropping ours entirely would mean the daemon can start before
    # .emacs.d exists on a fresh machine.
    unitConfig.After = lib.mkForce "graphical-session.target nyx-emacs-bootstrap.service";
    unitConfig.Wants = "nyx-emacs-bootstrap.service";

    # The daemon inherits the systemd user environment, which does not
    # include the Wayland session by default. Without these it starts
    # headless or falls back to XWayland, and emacsclient -c gives you a
    # frame that cannot properly open files or switch buffers.
    environment = {
      GDK_BACKEND = "wayland";
      XDG_SESSION_TYPE = "wayland";
      EGL_PLATFORM = "wayland";
    };

    # straight.el clones and byte-compiles every package on first run, which
    # takes far longer than systemd's default 90s start timeout. Without
    # this the daemon is killed mid-compile, restarted, and killed again,
    # burning CPU forever and never coming up.
    serviceConfig.TimeoutStartSec = "10min";
  };
}
