{ config, pkgs, lib, ... }:

# Nyx desktop, user side. Every colour comes from lib/melancholy.nix, so the
# bar, notifications, lock screen and terminal cannot drift apart.
#
# Hyprland config is written as Lua here rather than through home-manager's
# wayland.windowManager.hyprland module, whose serialiser emits invalid Lua
# for $mod, exec-once and col.active_border.

let
  t = import ../lib/melancholy.nix;

in
{
  # Hyprland 0.55 deprecated hyprlang; .conf support goes away in 0.57.
  # This is the Lua config, generated from the same Nix data.
  #
  # API, from the Hyprland wiki:
  #   hl.config({ section = { key = value } })      options
  #   hl.bind("SUPER + Return", hl.dsp.exec_cmd(x)) keybinds
  #   hl.dsp.window.close() / .float{action=} / .move{workspace=}
  #   hl.dsp.focus({ workspace = n })
  #
  # Anything I am not certain of is wrapped in pcall. A Lua *syntax* error
  # aborts the file and you get emergency binds only; a call to a nil field
  # does the same. pcall means one wrong dispatcher name costs you that bind
  # and nothing else. Remove the wrappers once each is confirmed.
  #
  # No exec-once here: waybar, mako, hypridle, hyprpaper, cliphist and
  # swayosd are all systemd user services now, which restart on failure and
  # do not re-spawn on every config reload.
  home.file.".config/hypr/hyprland.lua".text =
    let
      luaBind = keys: dispatch: ''pcall(function() hl.bind("${keys}", ${dispatch}) end)'';
      exec = cmd: ''hl.dsp.exec_cmd("${cmd}")'';
    in ''
      -- Generated by Nyx. Do not edit here; edit home/desktop.nix and rebuild.

      -- Declared explicitly: the scale was coming from somewhere outside
      -- this file, which meant a rebuild could not reproduce it.
      pcall(function()
        hl.monitor({ output = "eDP-1", mode = "1920x1080@60", position = "0x0", scale = 1.5 })
      end)

      hl.config({
        general = {
          gaps_in = 4,
          gaps_out = 8,
          border_size = 2,
          ["col.active_border"] = "${t.hypr t.amber}",
          ["col.inactive_border"] = "${t.hypr t.bgSubtle}",
          layout = "dwindle",
        },
        decoration = {
          rounding = 6,
          blur = { enabled = false },
        },
        animations = { enabled = true },
        cursor = {
          no_hardware_cursors = false,
        },
        input = {
          kb_layout = "us",
          follow_mouse = 1,
          touchpad = { natural_scroll = true },
        },
      })

      -- Applications
      ${luaBind "SUPER + T" (exec "ghostty")}
      ${luaBind "SUPER + E" (exec "emacsclient -c -a emacs")}
      ${luaBind "SUPER + B" (exec "brave")}
      ${luaBind "SUPER + SHIFT + B" (exec "firefox")}
      ${luaBind "SUPER + P" (exec "keepassxc")}
      ${luaBind "SUPER + N" (exec "nautilus")}
      ${luaBind "SUPER + C" (exec "qalculate-gtk")}
      ${luaBind "SUPER + A" (exec "ghostty -e claude")}
      ${luaBind "SUPER + D" (exec "nyx-dictate")}
      ${luaBind "SUPER + Space" (exec "fuzzel")}
      ${luaBind "SUPER + ALT + Space" (exec "nyx-menu-root")}
      ${luaBind "SUPER + K" (exec "ghostty -e less ${config.xdg.configHome}/nyx/keybinds.txt")}
      ${luaBind "SUPER + SHIFT + L" (exec "hyprlock")}

      -- Window management
      ${luaBind "SUPER + Q" "hl.dsp.window.close()"}
      ${luaBind "SUPER + V" ''hl.dsp.window.float({ action = "toggle" })''}

      -- SUPER+Return: maximise. Full width and height of the usable area,
      -- so Waybar stays visible. That is fullscreen mode 1 in Hyprland
      -- terms; mode 0 is true fullscreen and covers the bar.
      ${luaBind "SUPER + Return" ''hl.dsp.window.fullscreen({ mode = 1 })''}
      ${luaBind "SUPER + F" ''hl.dsp.window.fullscreen({ mode = 0 })''}

      -- Focus with SUPER + arrows, move the window with SUPER + SHIFT.
      ${luaBind "SUPER + left" ''hl.dsp.focus({ direction = "l" })''}
      ${luaBind "SUPER + right" ''hl.dsp.focus({ direction = "r" })''}
      ${luaBind "SUPER + up" ''hl.dsp.focus({ direction = "u" })''}
      ${luaBind "SUPER + down" ''hl.dsp.focus({ direction = "d" })''}

      ${luaBind "SUPER + SHIFT + left" ''hl.dsp.window.move({ direction = "l" })''}
      ${luaBind "SUPER + SHIFT + right" ''hl.dsp.window.move({ direction = "r" })''}
      ${luaBind "SUPER + SHIFT + up" ''hl.dsp.window.move({ direction = "u" })''}
      ${luaBind "SUPER + SHIFT + down" ''hl.dsp.window.move({ direction = "d" })''}

      -- Resize, since arrows are now the spatial keys.
      ${luaBind "SUPER + CTRL + left" ''hl.dsp.window.resize({ x = -60, y = 0 })''}
      ${luaBind "SUPER + CTRL + right" ''hl.dsp.window.resize({ x = 60, y = 0 })''}
      ${luaBind "SUPER + CTRL + up" ''hl.dsp.window.resize({ x = 0, y = -60 })''}
      ${luaBind "SUPER + CTRL + down" ''hl.dsp.window.resize({ x = 0, y = 60 })''}

      -- Workspaces
      for i = 1, 9 do
        pcall(function()
          hl.bind("SUPER + " .. i, hl.dsp.focus({ workspace = i }))
          hl.bind("SUPER + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
        end)
      end

      -- Capture
      ${luaBind "Print" (exec "nyx-shot clipboard")}
      ${luaBind "SHIFT + Print" (exec "nyx-shot edit")}
      ${luaBind "SUPER + Print" (exec "nyx-shot window")}
      ${luaBind "CTRL + Print" (exec "nyx-shot screen")}
      ${luaBind "SUPER + SHIFT + S" (exec "nyx-shot save")}
      ${luaBind "SUPER + SHIFT + R" (exec "nyx-record")}
      ${luaBind "SUPER + SHIFT + C" (exec "nyx-caffeine")}

      -- Window rules.
      --
      -- The function is hl.window_rule (underscore), not hl.windowrule --
      -- that earlier guess was silently swallowed by pcall, which is why
      -- nothing floated. Class matching is a regex, so anchor it.
      --
      -- Each rule gets its own pcall: one unsupported effect costs that
      -- rule alone rather than the whole block. Get real class strings
      -- from: hyprctl clients -j | jq -r '.[].class'
      local function rule(t) pcall(function() hl.window_rule(t) end) end

      rule({ match = { class = "^(org.keepassxc.KeePassXC)$" }, float = true })
      rule({ match = { class = "^(pavucontrol)$" }, float = true })
      rule({ match = { class = "^(org.pulseaudio.pavucontrol)$" }, float = true })
      rule({ match = { class = "^(qalculate-gtk)$" }, float = true })
      rule({ match = { class = "^(org.gnome.Nautilus)$" }, float = true })
      rule({ match = { class = "^(blueman-manager)$" }, float = true })
      rule({ match = { class = "^(nm-connection-editor)$" }, float = true })
      rule({ match = { class = "^(localsend_app)$" }, float = true })
      rule({ match = { title = "^(nyx-wallpaper)$" }, float = true })

      rule({ match = { class = "^(emacs)$" }, workspace = "1" })
      rule({ match = { class = "^(brave-browser)$" }, workspace = "2" })
      rule({ match = { class = "^(firefox)$" }, workspace = "2" })
      rule({ match = { class = "^(steam)$" }, workspace = "5" })

      -- Web apps: chromeless Brave windows, own class each.
      rule({ match = { class = "^(brave-web.whatsapp.com__-Default)$" }, workspace = "3" })
      rule({ match = { class = "^(brave-mail.proton.me__-Default)$" }, workspace = "3" })

      -- Media and brightness. locked = works on the lock screen.
      pcall(function()
        hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --output-volume raise"), { locked = true, repeating = true })
        hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --output-volume lower"), { locked = true, repeating = true })
        hl.bind("XF86AudioMute", hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"), { locked = true })
        hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("swayosd-client --brightness raise"), { locked = true, repeating = true })
        hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("swayosd-client --brightness lower"), { locked = true, repeating = true })
      end)
    '';

  # Cheatsheet. SUPER+K opens it.
  xdg.configFile."nyx/keybinds.txt".text = ''
    Nyx keybindings

    LAUNCH
      SUPER T             terminal (ghostty)
      SUPER E             emacsclient
      SUPER B             brave            SUPER SHIFT B    firefox
      SUPER P             keepassxc
      SUPER N             files (nautilus)
      SUPER C             calculator
      SUPER A             claude code
      SUPER D             dictation toggle
      SUPER Space         launcher (fuzzel)
      SUPER ALT Space     nyx menu
      SUPER K             this cheatsheet
      SUPER SHIFT C       caffeine (block idle lock/sleep)

    WINDOWS
      SUPER Return        maximise (keeps the bar visible)
      SUPER F             true fullscreen
      SUPER Q             close
      SUPER V             float
      SUPER arrows        move focus
      SUPER SHIFT arrows  move window
      SUPER CTRL arrows   resize

    WORKSPACES
      SUPER 1-9           switch
      SUPER SHIFT 1-9     move window to

    CAPTURE
      Print               region to clipboard
      SHIFT Print         region to satty
      SUPER Print         active window to clipboard
      CTRL Print          whole screen to clipboard
      SUPER SHIFT S       region saved to ~/Pictures/screenshots
      SUPER SHIFT R       record start/stop

    SESSION
      SUPER SHIFT L       lock
      power button        far right of the bar: suspend, reboot, shutdown
  '';

  # -------------------------------------------------------------------
  # Waybar
  # -------------------------------------------------------------------
  programs.waybar = {
    enable = true;
    systemd.enable = true;
    settings.mainBar = {
      layer = "top";
      position = "top";
      height = 34;
      spacing = 0;

      modules-left = [ "hyprland/workspaces" "hyprland/window" ];
      modules-center = [ "clock" ];
      modules-right = [
        # Bluetooth and network are handled by their tray applets
        # (blueman-applet, nm-applet), which carry both state and a click
        # menu. A Waybar module for either would only duplicate them.
        "tray" "custom/caffeine" "pulseaudio" "backlight" "battery"
        "custom/power"
      ];

      "custom/power" = {
        format = "󰐥";
        tooltip = true;
        tooltip-format = "Session: lock, suspend, reboot, shutdown, log out";
        on-click = "nyx-power";
      };

      "custom/caffeine" = {
        exec = "nyx-caffeine-status";
        return-type = "json";
        interval = 5;
        signal = 9;                 # nyx-caffeine sends SIGRTMIN+9
        on-click = "nyx-caffeine";
        format = "{}";
      };

      "hyprland/workspaces" = {
        format = "{name}";
        on-click = "activate";
      };

      "hyprland/window" = {
        format = "{title}";
        max-length = 48;
        separate-outputs = true;
      };

      clock = {
        format = "{:%a %d %b  %H:%M}";
        tooltip-format = "<tt>{calendar}</tt>";
        calendar.mode = "month";
      };

      # Every module below says what it is. A bare "40%" tells you nothing.
      pulseaudio = {
        format = "{icon} {volume}%";
        format-muted = "󰝟 muted";
        format-icons.default = [ "󰕿" "󰖀" "󰕾" ];
        tooltip-format = "{desc} at {volume}%";
        on-click = "pavucontrol";
        on-scroll-up = "swayosd-client --output-volume raise";
        on-scroll-down = "swayosd-client --output-volume lower";
      };

      backlight = {
        format = "{icon} {percent}%";
        format-icons = [ "󰃞" "󰃟" "󰃠" ];
        tooltip-format = "Screen brightness {percent}%";
        on-scroll-up = "swayosd-client --brightness raise";
        on-scroll-down = "swayosd-client --brightness lower";
      };

      battery = {
        format = "{icon} {capacity}%";
        format-charging = "󰂄 {capacity}%";
        format-plugged = "󰚥 {capacity}%";
        format-icons = [ "󰁺" "󰁼" "󰁾" "󰂀" "󰂂" ];
        # The number people actually want is time left, not percent.
        tooltip-format = "{timeTo}  ({power}W)";
        states = { warning = 25; critical = 12; };
        interval = 30;
      };

      tray = {
        spacing = 8;
        icon-size = 15;
      };
    };

    # Right-hand modules sit in one rounded group with even padding, rather
    # than a run of unlabelled numbers jammed against the screen edge.
    style = ''
      * {
        font-family: "CommitMono Nerd Font Mono", monospace;
        font-size: 12px;
        min-height: 0;
      }

      window#waybar {
        background: ${t.bg};
        color: ${t.fg};
        border-bottom: 1px solid ${t.bgSubtle};
      }

      #workspaces {
        margin: 4px 0 4px 8px;
      }
      #workspaces button {
        color: ${t.fgMuted};
        padding: 0 8px;
        border-radius: 4px;
        background: transparent;
      }
      #workspaces button.active {
        color: ${t.bg};
        background: ${t.amber};
      }
      #workspaces button.urgent { color: ${t.red}; }
      #workspaces button:hover  { color: ${t.fg}; background: ${t.bgSubtle}; }

      #window {
        color: ${t.fgMuted};
        margin-left: 10px;
      }
      window#waybar.empty #window { background: transparent; }

      #clock {
        color: ${t.fg};
        font-weight: bold;
      }

      /* One pill for the status cluster, tray included, power on the end. */
      #custom-caffeine, #pulseaudio, #backlight, #battery,
      #tray, #custom-power {
        background: ${t.bgSubtle};
        padding: 0 10px;
        margin: 5px 0;
        font-size: 15px;
      }
      #custom-caffeine { border-radius: 6px 0 0 6px; margin-left: 8px; }
      #custom-power    { border-radius: 0 6px 6px 0; margin-right: 8px; }

      #custom-caffeine.on  { color: ${t.amber}; }
      #custom-caffeine.off { color: ${t.fgMuted}; }
      #pulseaudio   { color: ${t.cyan}; }
      #backlight    { color: ${t.fg}; }
      #battery      { color: ${t.green}; }
      #custom-power { color: ${t.red}; }
      #custom-power:hover { color: ${t.bg}; background: ${t.red}; }

      #battery.warning  { color: ${t.amber}; }
      #battery.critical { color: ${t.bg}; background: ${t.red}; }
      #battery.charging { color: ${t.green}; }

      tooltip {
        background: ${t.bg};
        border: 1px solid ${t.amber};
        border-radius: 6px;
      }
      tooltip label { color: ${t.fg}; padding: 4px; }
    '';
  };

  # -------------------------------------------------------------------
  # Notifications
  # -------------------------------------------------------------------
  services.cliphist.enable = true;

  services.mako = {
    enable = true;
    settings = {
      background-color = t.bg;
      text-color = t.fg;
      border-color = t.amber;
      border-size = 2;
      border-radius = 6;
      default-timeout = 5000;
      font = "Raleway 11";
    };
  };

  # -------------------------------------------------------------------
  # Launcher
  # -------------------------------------------------------------------
  programs.fuzzel = {
    enable = true;
    settings = {
      main.font = "CommitMono Nerd Font Mono:size=12";
      colors = {
        background = "${lib.removePrefix "#" t.bg}ee";
        text = "${lib.removePrefix "#" t.fg}ff";
        match = "${lib.removePrefix "#" t.amber}ff";
        selection = "${lib.removePrefix "#" t.bgSubtle}ff";
        selection-text = "${lib.removePrefix "#" t.fgString}ff";
        border = "${lib.removePrefix "#" t.amber}ff";
      };
    };
  };

  # -------------------------------------------------------------------
  # Lock and idle
  # -------------------------------------------------------------------
  programs.hyprlock = {
    enable = true;
    settings = {
      general = {
        hide_cursor = true;
        grace = 2;              # a stray keypress within 2s dismisses it
        no_fade_in = false;
      };

      background = [{
        path = "${../assets/wallpapers/dark-abstract.png}";
        blur_passes = 3;
        blur_size = 8;
        brightness = 0.6;
      }];

      label = [
        {
          # Clock
          text = "$TIME";
          color = t.fg;
          font_size = 92;
          font_family = "CommitMono Nerd Font Mono";
          position = "0, 220";
          halign = "center";
          valign = "center";
        }
        {
          # Date
          text = ''cmd[update:60000] date +"%A, %d %B"'';
          color = t.fgMuted;
          font_size = 20;
          font_family = "Raleway";
          position = "0, 140";
          halign = "center";
          valign = "center";
        }
        {
          # Who is logged in
          text = "$USER";
          color = t.amber;
          font_size = 14;
          font_family = "Raleway";
          position = "0, -110";
          halign = "center";
          valign = "center";
        }
      ];

      input-field = [{
        size = "320, 52";
        outline_thickness = 2;
        dots_size = 0.28;
        dots_spacing = 0.3;
        dots_center = true;
        outer_color = t.amber;
        inner_color = t.bgSubtle;
        font_color = t.fg;
        check_color = t.cyan;
        fail_color = t.red;
        fail_text = "$FAIL";
        placeholder_text = "";
        rounding = 8;
        position = "0, -40";
        halign = "center";
        valign = "center";
      }];
    };
  };

  services.hypridle = {
    enable = true;
    settings = {
      general = {
        lock_cmd = "pidof hyprlock || hyprlock";
        before_sleep_cmd = "loginctl lock-session";
        after_sleep_cmd = "nyx-dpms on";
      };
      listener = [
        { timeout = 240; on-timeout = "brightnessctl -s set 10"; on-resume = "brightnessctl -r"; }
        { timeout = 300; on-timeout = "loginctl lock-session"; }
        { timeout = 360; on-timeout = "nyx-dpms off"; on-resume = "nyx-dpms on"; }
        { timeout = 900; on-timeout = "systemctl suspend"; }
      ];
    };
  };

  # -------------------------------------------------------------------
  # Terminal
  # -------------------------------------------------------------------
  programs.ghostty = {
    enable = true;
    settings = {
      font-family = "CommitMono Nerd Font Mono";
      font-size = 11;
      background = t.bg;
      foreground = t.fg;
      cursor-color = t.cyan;
      selection-background = t.bgSubtle;
      selection-foreground = t.fgString;
      background-opacity = 0.96;
      window-padding-x = 10;
      window-padding-y = 10;
      palette = lib.mapAttrsToList
        (n: v: "${lib.removePrefix "color" n}=${v}") t.ansi;
    };
  };
}
