{ config, pkgs, lib, ... }:

# Nyx desktop, user side. Every colour comes from lib/melancholy.nix, so the
# bar, notifications, lock screen and terminal cannot drift apart.
#
# NOTE ON HYPRLAND: we generate hyprland.lua ourselves rather than using
# home-manager's wayland.windowManager.hyprland module. The module's
# serialiser produced invalid Lua for us three times running ($mod,
# exec-once, col.active_border). Writing the Lua directly means the file on
# disk is the file we wrote, and the Hyprland wiki is the only reference we
# need.

let
  t = import ../lib/melancholy.nix;

  binds = [
    "SUPER, Return, exec, ghostty"
    "SUPER, E, exec, emacsclient -c -a ''"
    "SUPER, B, exec, brave"
    "SUPER SHIFT, B, exec, firefox"
    "SUPER, P, exec, keepassxc"
    "SUPER, Space, exec, fuzzel"
    "SUPER ALT, Space, exec, nyx-menu-root"
    "SUPER, K, exec, ghostty -e less ${config.xdg.configHome}/nyx/keybinds.txt"
    "SUPER, Q, killactive,"
    "SUPER, F, fullscreen,"
    "SUPER, V, togglefloating,"
    "SUPER SHIFT, L, exec, hyprlock"
    ", Print, exec, grim -g \"$(slurp)\" - | wl-copy"
    "SHIFT, Print, exec, grim -g \"$(slurp)\" - | satty -f -"
    "SUPER SHIFT, R, exec, wf-recorder -g \"$(slurp)\" -f $HOME/Videos/rec-$(date +%s).mp4"
  ]
  ++ builtins.concatLists (builtins.genList
    (i: let ws = toString (i + 1); in [
      "SUPER, ${ws}, workspace, ${ws}"
      "SUPER SHIFT, ${ws}, movetoworkspace, ${ws}"
    ]) 9);

  mediaBinds = [
    ",XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise"
    ",XF86AudioLowerVolume, exec, swayosd-client --output-volume lower"
    ",XF86AudioMute, exec, swayosd-client --output-volume mute-toggle"
    ",XF86MonBrightnessUp, exec, swayosd-client --brightness raise"
    ",XF86MonBrightnessDown, exec, swayosd-client --brightness lower"
  ];
in
{
  # Hyprland 0.55 deprecated hyprlang; .conf support goes away in 0.57.
  # This is the Lua config, generated from the same Nix data.
  #
  # API, from the Hyprland wiki:
  #   hl.config({ section = { key = value } })      options
  #   hl.bind("SUPER + Return", hl.dsp.exec_cmd(x)) keybinds
  #   hl.dsp.window.close() / .float{action=} / .move{workspace=}
  #   hl.dsp.focus({ workspace = n })
  #
  # Anything I am not certain of is wrapped in pcall. A Lua *syntax* error
  # aborts the file and you get emergency binds only; a call to a nil field
  # does the same. pcall means one wrong dispatcher name costs you that bind
  # and nothing else. Remove the wrappers once each is confirmed.
  #
  # No exec-once here: waybar, mako, hypridle, hyprpaper, cliphist and
  # swayosd are all systemd user services now, which restart on failure and
  # do not re-spawn on every config reload.
  home.file.".config/hypr/hyprland.lua".text =
    let
      luaBind = keys: dispatch: ''pcall(function() hl.bind("${keys}", ${dispatch}) end)'';
      exec = cmd: ''hl.dsp.exec_cmd("${cmd}")'';
    in ''
      -- Generated by Nyx. Do not edit here; edit home/desktop.nix and rebuild.

      hl.config({
        general = {
          gaps_in = 4,
          gaps_out = 8,
          border_size = 2,
          ["col.active_border"] = "${t.hypr t.amber}",
          ["col.inactive_border"] = "${t.hypr t.bgSubtle}",
          layout = "dwindle",
        },
        decoration = {
          rounding = 6,
          blur = { enabled = false },
        },
        animations = { enabled = true },
        input = {
          kb_layout = "us",
          follow_mouse = 1,
          touchpad = { natural_scroll = true },
        },
      })

      -- Applications
      ${luaBind "SUPER + Return" (exec "ghostty")}
      ${luaBind "SUPER + E" (exec "emacsclient -c -a emacs")}
      ${luaBind "SUPER + B" (exec "brave")}
      ${luaBind "SUPER + SHIFT + B" (exec "firefox")}
      ${luaBind "SUPER + P" (exec "keepassxc")}
      ${luaBind "SUPER + Space" (exec "fuzzel")}
      ${luaBind "SUPER + ALT + Space" (exec "nyx-menu-root")}
      ${luaBind "SUPER + K" (exec "ghostty -e less ${config.xdg.configHome}/nyx/keybinds.txt")}
      ${luaBind "SUPER + SHIFT + L" (exec "hyprlock")}

      -- Window management
      ${luaBind "SUPER + Q" "hl.dsp.window.close()"}
      ${luaBind "SUPER + V" ''hl.dsp.window.float({ action = "toggle" })''}
      ${luaBind "SUPER + F" ''hl.dsp.window.fullscreen({ action = "toggle" })''}

      -- Workspaces
      for i = 1, 9 do
        pcall(function()
          hl.bind("SUPER + " .. i, hl.dsp.focus({ workspace = i }))
          hl.bind("SUPER + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
        end)
      end

      -- Capture
      ${luaBind "Print" (exec "grim -g \"$(slurp)\" - | wl-copy")}
      ${luaBind "SHIFT + Print" (exec "grim -g \"$(slurp)\" - | satty -f -")}
      ${luaBind "SUPER + SHIFT + R" (exec "nyx-record")}

      -- Media and brightness. locked = works on the lock screen.
      pcall(function()
        hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --output-volume raise"), { locked = true, repeating = true })
        hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --output-volume lower"), { locked = true, repeating = true })
        hl.bind("XF86AudioMute", hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"), { locked = true })
        hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("swayosd-client --brightness raise"), { locked = true, repeating = true })
        hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("swayosd-client --brightness lower"), { locked = true, repeating = true })
      end)
    '';

  # Cheatsheet. SUPER+K opens it.
  xdg.configFile."nyx/keybinds.txt".text = ''
    Nyx keybindings

    SUPER Return        terminal (ghostty)
    SUPER E             emacsclient
    SUPER B             brave          SUPER SHIFT B   firefox
    SUPER P             keepassxc
    SUPER Space         launcher (fuzzel)
    SUPER ALT Space     nyx menu
    SUPER K             this cheatsheet
    SUPER Q             close window
    SUPER F             fullscreen     SUPER V         float
    SUPER SHIFT L       lock
    SUPER 1-9           workspace      SUPER SHIFT 1-9 move to workspace
    Print               region to clipboard
    SHIFT Print         region to satty
    SUPER SHIFT R       record region to ~/Videos
  '';

  # -------------------------------------------------------------------
  # Waybar
  # -------------------------------------------------------------------
  programs.waybar = {
    enable = true;
    systemd.enable = true;
    settings.mainBar = {
      layer = "top";
      position = "top";
      height = 30;
      modules-left = [ "hyprland/workspaces" ];
      modules-center = [ "clock" ];
      modules-right = [ "pulseaudio" "backlight" "battery" "network" "tray" ];

      clock.format = "{:%a %d %b  %H:%M}";
      battery = {
        format = "{icon} {capacity}%";
        format-icons = [ "" "" "" "" "" ];
        states = { warning = 30; critical = 15; };
      };
      network.format-wifi = "  {essid}";
      pulseaudio.format = "  {volume}%";
      backlight.format = "  {percent}%";
    };

    style = ''
      * {
        font-family: "CommitMono Nerd Font Mono", monospace;
        font-size: 12px;
      }
      window#waybar {
        background: ${t.bg};
        color: ${t.fg};
        border-bottom: 2px solid ${t.bgSubtle};
      }
      #workspaces button          { color: ${t.fgMuted}; padding: 0 8px; }
      #workspaces button.active   { color: ${t.amber}; }
      #workspaces button.urgent   { color: ${t.red}; }
      #clock                      { color: ${t.cyan}; }
      #battery                    { color: ${t.green}; }
      #battery.warning            { color: ${t.amber}; }
      #battery.critical           { color: ${t.red}; }
      #network, #pulseaudio, #backlight { color: ${t.fg}; padding: 0 8px; }
    '';
  };

  # -------------------------------------------------------------------
  # Notifications
  # -------------------------------------------------------------------
  services.cliphist.enable = true;

  services.mako = {
    enable = true;
    settings = {
      background-color = t.bg;
      text-color = t.fg;
      border-color = t.amber;
      border-size = 2;
      border-radius = 6;
      default-timeout = 5000;
      font = "Raleway 11";
    };
  };

  # -------------------------------------------------------------------
  # Launcher
  # -------------------------------------------------------------------
  programs.fuzzel = {
    enable = true;
    settings = {
      main.font = "CommitMono Nerd Font Mono:size=12";
      colors = {
        background = "${lib.removePrefix "#" t.bg}ee";
        text = "${lib.removePrefix "#" t.fg}ff";
        match = "${lib.removePrefix "#" t.amber}ff";
        selection = "${lib.removePrefix "#" t.bgSubtle}ff";
        selection-text = "${lib.removePrefix "#" t.fgString}ff";
        border = "${lib.removePrefix "#" t.amber}ff";
      };
    };
  };

  # -------------------------------------------------------------------
  # Lock and idle
  # -------------------------------------------------------------------
  programs.hyprlock = {
    enable = true;
    settings = {
      background = [{ color = t.bg; }];
      input-field = [{
        size = "300, 50";
        outline_thickness = 2;
        outer_color = t.amber;
        inner_color = t.bgSubtle;
        font_color = t.fg;
        placeholder_text = "";
      }];
    };
  };

  services.hypridle = {
    enable = true;
    settings = {
      general = {
        lock_cmd = "pidof hyprlock || hyprlock";
        before_sleep_cmd = "loginctl lock-session";
        after_sleep_cmd = "hyprctl dispatch dpms on";
      };
      listener = [
        { timeout = 240; on-timeout = "brightnessctl -s set 10"; on-resume = "brightnessctl -r"; }
        { timeout = 300; on-timeout = "loginctl lock-session"; }
        { timeout = 360; on-timeout = "hyprctl dispatch dpms off"; on-resume = "hyprctl dispatch dpms on"; }
        { timeout = 900; on-timeout = "systemctl suspend"; }
      ];
    };
  };

  # -------------------------------------------------------------------
  # Terminal
  # -------------------------------------------------------------------
  programs.ghostty = {
    enable = true;
    settings = {
      font-family = "CommitMono Nerd Font Mono";
      font-size = 11;
      background = t.bg;
      foreground = t.fg;
      cursor-color = t.cyan;
      selection-background = t.bgSubtle;
      selection-foreground = t.fgString;
      background-opacity = 0.96;
      window-padding-x = 10;
      window-padding-y = 10;
      palette = lib.mapAttrsToList
        (n: v: "${lib.removePrefix "color" n}=${v}") t.ansi;
    };
  };
}
